### ISSUE TITLE
Error during browser action initialization

### ISSUE THREAD

**Issue by KennethS3107** [rharel/webext-private-bookmarks#177] opened 2021-11-09 02:00 UTC
Debug info: `Could not establish connection. Receiving end does not exist.`
Private Bookmarks, no access to open, received an error message to effect that 
"Oops there is an error, you can help by reporting it.

Private Bookmarks is still in early development"

**Comment by realpixelcode** [comment] 2022-05-23 08:06
Duplicate of #104

**Closed** 2022-06-12 16:06 UTC
Labels: is: duplicate
