### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by heapsofit** [rharel/webext-private-bookmarks#83] opened 2018-08-27 01:26 UTC
For bug reports, please fill in:
 - Firefox version: FF 61.0.2
 - Operating system: Win10
 - Steps to reproduce: Not sure, seems to be random on opening or closing  
 - What was the expected behavior:  not crashing
 - What was the actual behavior:  crashing FF  

It is assumed that you are using the latest version of Private Bookmarks.

**Comment by rharel** [comment] 2018-08-27 17:28
I'm very skeptical about an extension being the cause of a crash (especially since you say it is happening randomly). The issue is most likely in Firefox itself so unfortunately I cannot do anything about it, sorry :(

**Comment by rharel** [comment] 2018-08-27 17:29
Just out of curiosity, when you say "opening and closing", what do you mean? Opening/closing of the browser?

**Comment by heapsofit** [comment] 2018-08-29 02:03
When I said randomly, of course, I meant randomly when using the extension, not when the extension is not in use.  The crashes occur mostly when the extension is closed.  Don't say you are very skeptical, it is disrespectful to people trying to help by reporting issues, I could easily just uninstall and forget it.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by rharel** [comment] 2018-08-29 06:08
Sorry about the miscommunication, I am not skeptical that Firefox crashes,
nor that it crashes only with PB installed, just that the underlying cause
is in PB. Firefox exposes a limited set of tools for extensions to use, and
by design use of  these tools should not ever cause a crash (it is
Firefox's responsibility to ensure that). Therefore all I'm saying is that
apparently PB and something about the Firefox installation on your machine
is revealing this bug in Firefox. If you happen to notice a pattern of
interaction that reproduces the crash reliably, I'll be happy to see what I
can do to avoid it from PB's side, and I'll also report the bug to Firefox
developers. But if not, the only reccommendation I can make is try
reinstalling either FF or PB, or just uninstall PB. Sorry I couldn't be of
more help. Raoul

**Closed** 2018-09-16 11:53 UTC
Labels: type: firefox-bug
