### ISSUE TITLE
Hiding "Private Bookmarks" outside of private browsing

### ISSUE THREAD

**Issue by dekeltal** [rharel/webext-private-bookmarks#25] opened 2017-11-09 19:20 UTC
The default (and sensible) option is to disable the "Private Bookmarks" item outside private browsing. When working outside private browsing there's actually no use for the disabled item, and it would be useful to have it hidden in that case (at least as an option).

Great work!
Thanks!

**Comment by rharel** [comment] 2017-11-09 22:13
Are you using Firefox 58 Beta? This may be a duplicate of #22, i.e. this is a problem in Firefox itself and we should wait for it to be fixed.

**Comment by dekeltal** [comment] 2017-11-09 22:16
This is not a problem, but an enhancement request. It would be great to have the option to HIDE the menu item when not in private browsing, rather just have it disabled.

**Comment by rharel** [comment] 2017-11-09 22:17
Sorry, I need some clarification: are you referring to the button at the address bar, or the main one which opens the menu panel with options to lock, change password etc.?

**Comment by dekeltal** [comment] 2017-11-09 22:21
The main one. When outside private browsing it's disabled - I think it
would be usedful to have the option to have it hidden outside private
browsing (instead of disabled). Thanks!

**Comment by rharel** [comment] 2017-11-09 22:28
Ah I see. Yes I would prefer that too, but as far as I can tell currently this functionality is simply not available in the WebExtension APIs :( so it is out of my hands and up to the Firefox developers to implement it. If they ever do, then I will be sure to make use of it!

The best I can advise you, if you are using Firefox 57+, is to pin the icon to the Overflow Menu (e.g. `right-click` icon => `Pin to Overflow Menu`. This way it is at least out of sight. Thanks for your feedback!

**Closed by rharel** 2017-11-09 22:28 UTC
Labels: duplicate

**Comment by dekeltal** [comment] 2017-11-09 22:31
Thanks for the prompt response.
Keep up the good job!
